"""
OxWg Panel - Services Package
=============================
Core business logic layer independent of Flask blueprint routing.
"""
from services.errors import (
    WGPanelError,
    AddressAllocationError,
    WireGuardError,
    SchemaMigrationError,
    ShortLinkError,
    ClientConfigIncomplete,
    NodeClientError,
)

from services.node_client import (
    _node_payload,
    node_get,
    node_post,
    node_delete,
)

from services.peer_profiles import (
    _DEF_PROFILE,
    _migrate_single_profile,
    _load_profiles,
    _save_profiles,
    _get_profile,
    _set_profile,
    _set_active_profile,
    _delete_profile,
    _panel_default_dns,
)

from services.subscription_profiles import (
    _load_subscription_profiles,
    _save_subscription_profiles,
    _sanitize_subscription_profile,
    _subscription_profile_rows,
    _get_subscription_profile,
    _set_subscription_profile,
    _delete_subscription_profile,
    _set_active_subscription_profile,
)

from services.panel_settings import (
    _load_panel_settings,
    _save_panel_settings,
    _load_runtime,
    _save_runtime,
    _panel_base,
    _is_https,
    _panel_timezone_name,
    _panel_timezone,
    _valid_timezone_name,
    _detect_system_timezone_name,
    _norm_hostport,
    _server_host,
    _panel_local_datetime,
    _panel_display_datetime,
    _panel_filename_stamp,
    _utc_timestamp_iso,
    _panel_filter_datetime_utc_naive,
)

from services.admin_log import (
    _norm_adminlog,
    logpanel_action,
    _read_admin_logs,
    _whoami_logs,
)

from services.log_retention import (
    _load_log_settings,
    _save_log_settings,
    _log_save,
    _auto_trim,
    _load_retention,
    _save_retention,
    _may_autoclear,
    _start_retention,
    _retention_loop,
    _clear_retention,
    run_log,
)

from services.telegram_notifier import (
    _load_tg_settings,
    _save_tg_settings,
    _load_tg_admins,
    _save_tg_admins,
    _send_telegram_event,
    _tg_event_key,
    _tg_human_duration,
    _tg_human_datetime,
    _tg_human_bytes,
    _TG_EVENT_LOCK,
    _TG_EVENT_LAST,
    _tg_event_escape,
    _tg_now_text,
    _tg_chatid,
    _send_zip_telegram,
    _security_notify_enabled,
    _send_security_notification,
)

from services.shortlink_service import (
    _token,
    _shortlink_url,
    _shortlink_for_peer,
    _shortlink_response_for_peer,
    _peer_from_shortlink_token,
    _shortlink_from_peer_id,
    _delete_shortlinks_for_peer_ids,
)

from services.update_checker import (
    _project_version,
    PANEL_VERSION,
    PANEL_REPO,
    PANEL_UPDATE_TTL,
    _PANEL_UPDATE_CACHE,
    _version_tuple,
    _github_latest_panel_version,
    check_panel_update,
)

from services.wg_parser import (
    find_iface,
    _derive_wg_public_key,
    _copy_local_iface_from_parsed,
    _valid_wg_key,
    _assign_iface_public_key,
    _iface_is_node,
    iface_devname,
    _node_id_from_iface,
    _public_key_from_node_payload,
    _persist_iface_public_key,
    _fetch_node_iface_public_key,
)

from services.backup_service import (
    _start_backup_scheduler,
    _backup_scheduler_loop,
    _load_backup_settings,
    _save_backup_settings,
    _load_backup_schedule,
    _save_backup_schedule,
    _save_autobackup,
    _cron_field_match,
    _backup_due_slot,
)

from services.node_monitor import (
    _node_notify_monitor,
    _start_node_notify_monitor,
    _load_node_notification_state,
    _save_node_notification_state,
    _local_notification_states,
    _check_local_notifications,
    _check_node_notifications,
    _read_update_status,
    _check_update_notifications,
    set_app as set_node_monitor_app,
)

from services.http_security import (
    _load_http_security_settings,
    _save_http_security_settings,
    _http_security_is_trusted,
    _http_security_is_denied,
    _http_security_is_temporarily_allowed,
    _http_security_client_ip,
    _http_security_scope_applies,
    _start_http_security_cleanup,
    _HTTP_SECURITY_NFT_TABLE,
    _http_security_nft_install_command,
    _http_security_nft_status,
    _http_security_nft_run_script,
    _http_security_nft_ensure,
    _http_security_firewall_add,
    _http_security_firewall_remove,
    _request_client_ip,
    _request_device_summary,
)

from services.peer_lifecycle import (
    _run_expiry_once,
    _start_expiry_enforcer,
    _on_boot,
    repoint_endpoints,
    _expire,
    _latest_handshake,
    _accumulate_peer_usage,
    _effective_expiry_ts,
    _conv_time_limit,
    _disable_peer,
    _wg_disable_peer_quiet,
    _peer_conn_status,
    _wg_runtime_snapshot,
    set_app as set_peer_lifecycle_app,
)

from services.config_generator import (
    _effective_dns,
    _effective_client_endpoint,
    _client_conf_txt,
    _client_config_txt,
    _peer_client_conf_or_502,
    resolve_client_endpoint,
    _server_publickey,
    remote_iface_name,
    _node_endpoint_fallback,
    resolve_client_endpoint_cheap,
)

from services.subscription_service import (
    subscription_access,
    _subscription_inbound_state,
    _subscription_access_or_403,
    _subscription_public_payload,
    _flag_from_cc,
)

__all__ = [
    # Errors
    "WGPanelError",
    "AddressAllocationError",
    "WireGuardError",
    "SchemaMigrationError",
    "ShortLinkError",
    "ClientConfigIncomplete",
    "NodeClientError",
    # Node client
    "_node_payload",
    "node_get",
    "node_post",
    "node_delete",
    # Peer profiles
    "_DEF_PROFILE",
    "_migrate_single_profile",
    "_load_profiles",
    "_save_profiles",
    "_get_profile",
    "_set_profile",
    "_set_active_profile",
    "_delete_profile",
    "_panel_default_dns",
    # Subscription profiles
    "_load_subscription_profiles",
    "_save_subscription_profiles",
    "_sanitize_subscription_profile",
    "_subscription_profile_rows",
    "_get_subscription_profile",
    "_set_subscription_profile",
    "_delete_subscription_profile",
    "_set_active_subscription_profile",
    # Panel settings
    "_load_panel_settings",
    "_save_panel_settings",
    "_load_runtime",
    "_save_runtime",
    "_panel_base",
    "_is_https",
    "_panel_timezone_name",
    "_panel_timezone",
    "_valid_timezone_name",
    "_detect_system_timezone_name",
    "_norm_hostport",
    "_server_host",
    "_panel_local_datetime",
    "_panel_display_datetime",
    "_panel_filename_stamp",
    "_utc_timestamp_iso",
    "_panel_filter_datetime_utc_naive",
    # Admin log
    "_norm_adminlog",
    "logpanel_action",
    "_read_admin_logs",
    "_whoami_logs",
    # Log retention
    "_load_log_settings",
    "_save_log_settings",
    "_log_save",
    "_auto_trim",
    "_load_retention",
    "_save_retention",
    "_may_autoclear",
    "_start_retention",
    "_retention_loop",
    "_clear_retention",
    "run_log",
    # Telegram notifier
    "_load_tg_settings",
    "_save_tg_settings",
    "_load_tg_admins",
    "_save_tg_admins",
    "_send_telegram_event",
    "_tg_event_key",
    "_tg_human_duration",
    "_tg_human_datetime",
    "_tg_human_bytes",
    "_TG_EVENT_LOCK",
    "_TG_EVENT_LAST",
    "_tg_event_escape",
    "_tg_now_text",
    "_tg_chatid",
    "_send_zip_telegram",
    "_security_notify_enabled",
    "_send_security_notification",
    # Shortlink service
    "_token",
    "_shortlink_url",
    "_shortlink_for_peer",
    "_shortlink_response_for_peer",
    "_peer_from_shortlink_token",
    "_shortlink_from_peer_id",
    "_delete_shortlinks_for_peer_ids",
    # Update checker
    "_project_version",
    "PANEL_VERSION",
    "PANEL_REPO",
    "PANEL_UPDATE_TTL",
    "_PANEL_UPDATE_CACHE",
    "_version_tuple",
    "_github_latest_panel_version",
    "check_panel_update",
    # WG parser
    "find_iface",
    "_derive_wg_public_key",
    "_copy_local_iface_from_parsed",
    "_valid_wg_key",
    "_assign_iface_public_key",
    "_iface_is_node",
    "iface_devname",
    "_node_id_from_iface",
    "_public_key_from_node_payload",
    "_persist_iface_public_key",
    "_fetch_node_iface_public_key",
    # Backup service
    "_start_backup_scheduler",
    "_backup_scheduler_loop",
    "_load_backup_settings",
    "_save_backup_settings",
    "_load_backup_schedule",
    "_save_backup_schedule",
    "_save_autobackup",
    "_cron_field_match",
    "_backup_due_slot",
    # Node monitor
    "_node_notify_monitor",
    "_start_node_notify_monitor",
    "_load_node_notification_state",
    "_save_node_notification_state",
    "_local_notification_states",
    "_check_local_notifications",
    "_check_node_notifications",
    "_read_update_status",
    "_check_update_notifications",
    "set_node_monitor_app",
    # HTTP security
    "_load_http_security_settings",
    "_save_http_security_settings",
    "_http_security_is_trusted",
    "_http_security_is_denied",
    "_http_security_is_temporarily_allowed",
    "_http_security_client_ip",
    "_http_security_scope_applies",
    "_start_http_security_cleanup",
    "_HTTP_SECURITY_NFT_TABLE",
    "_http_security_nft_install_command",
    "_http_security_nft_status",
    "_http_security_nft_run_script",
    "_http_security_nft_ensure",
    "_http_security_firewall_add",
    "_http_security_firewall_remove",
    "_request_client_ip",
    "_request_device_summary",
    # Peer lifecycle
    "_run_expiry_once",
    "_start_expiry_enforcer",
    "_on_boot",
    repoint_endpoints,
    "_expire",
    "_latest_handshake",
    "_accumulate_peer_usage",
    "_effective_expiry_ts",
    "_conv_time_limit",
    "_disable_peer",
    "_wg_disable_peer_quiet",
    "_peer_conn_status",
    "_wg_runtime_snapshot",
    "set_peer_lifecycle_app",
    # Config generator
    "_effective_dns",
    "_effective_client_endpoint",
    "_client_conf_txt",
    "_client_config_txt",
    "_peer_client_conf_or_502",
    "resolve_client_endpoint",
    "_server_publickey",
    "remote_iface_name",
    "_node_endpoint_fallback",
    "resolve_client_endpoint_cheap",
    # Subscription service
    "subscription_access",
    "_subscription_inbound_state",
    "_subscription_access_or_403",
    "_subscription_public_payload",
    "_flag_from_cc",
]
